name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  pull_request:
    branches: [ "main" ]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote 
        env:
          HF: ${{ secrets.HUGGINGFACE }}
        run: git remote add space https://huggingface.co/spaces/zaidmehdi/arabic-dialect-classifier
      - name: Push to hub
        env:
          HF: ${{ secrets.HUGGINGFACE }}
        run: git push --force https://huggingface.co/spaces/zaidmehdi/arabic-dialect-classifier
